# Generated by Django 4.2.8 on 2024-01-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.vecteezy.com/vector-art/3170825-isolated-food-plate-fork-and-spoon-vector-design', max_length=500),
        ),
    ]
