# Generated by Django 4.2.8 on 2024-05-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productreview_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='parent_review_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
