# Generated by Django 4.2.8 on 2024-05-12 18:36

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_productreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='rid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcd12345', length=10, max_length=20, null=True, prefix='REV'),
        ),
    ]
