# Generated by Django 4.2.8 on 2024-05-12 18:37

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productreview_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcd12345', length=10, max_length=20, prefix='REV', unique=True),
        ),
    ]
