# Generated by Django 4.2.8 on 2024-11-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_productreview_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('deliverd', 'Delivered')], default='processing', max_length=30),
        ),
    ]
